export { EventsFormsIndex as General } from './General'
export { EventsFormsRegistration as Registration } from './Registration'
export { EventsFormsOptional as Optional } from './Optional'
export { EventsFormsComments as Comments } from './Comments'
export { EventsFormsImages as Images } from './Images'
export { EventsFormsOrganizer as Organizer } from './Organizer'
export { EventFormsActions as Actions } from './actions/Actions'
export { default as Registrees } from './Registrees'
export * from './MainLayout'