// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0a183bba-3988-4f74-96ec-529d82308806",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Moh49p0u6",
    "aws_user_pools_web_client_id": "1n34i0b5dpu8sqjo87m12fi3rg",
    "aws_user_files_s3_bucket": "carteleraeventsimages",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
