// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:0d28b161-2296-420e-bf27-55a558578253',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'teccartelera-hosting-mobilehub-1325484078',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1isbo4xxjoum8.cloudfront.net',
    'aws_mobile_analytics_app_id': 'd717e4982b724ed398919c35f75a38ba',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '178cf6c2-3df5-41fd-aec3-7005e76ceace',
    'aws_project_name': 'tec-cartelera',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'teccartelera-mobilehub-1325484078',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'teccartelera-userfiles-mobilehub-1325484078',
    'aws_user_files_s3_bucket_region': 'us-east-1',
}

export default awsmobile;
